# Generated by Django 5.2 on 2025-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_whatsappmessage_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
